trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: '1OctAzure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t divcontainer.azurecr.io/web-game:tag 2048-game
      az acr login -n divcontainer
      docker push divcontainer.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '1OctAzure'
    azureResourceGroup: 'DivDevOps'
    kubernetesCluster: 'app066'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: '1OctAzure'
    azureContainerRegistry: 'divcontainer.azurecr.io'
    forceUpdate: false